/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JuegoSerpiente;

public class App {


    public static void main(String[] args) {
        new JuegoVentana();
    }
}
